services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb://mongo:27017/rap"
      API_GPT: ""
      ENVIRONMENT: "local"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    networks:
      - leniser-wpp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - leniser-wpp
    volumes:
      - mongo_data:/data/db
      - ./src/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  app_data:
  mongo_data:

networks:
  leniser-wpp:
    driver: bridge
